version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:2.18.4
    command:
      - --tunnel-port=3000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 3000:3000
      - 9443:9443

volumes:
  portainer_data: